### PR TITLE
Add a github pages UI to create and download templates as a zip (using JsZip)

### PR DESCRIPTION
**Pull request by propstg**
Adds a simple github pages UI to let a user fill out the form for their template in their browser, and download it as a zip file. "Author" and "Mod Name" drive the defaults for "GUID" and "Namespace", but both can be customized if desired. The contents of this PR are available here: https://propstg.github.io/plateup-template-builder/

Also adds an `npm run build-gh` script to generate the list of files in UnityProject to add to the zip, which would just need to be ran whenever files are added or removed from the UnityProject template.

If merged, you'll probably need to set Pages up for your project:
image

### CODE REVIEW

**Comment by StarFluxGames** [comment]
Looks great!

Could you please add support for my latest commit which includes `.git` building, then it's good to go!

**Comment by propstg** [comment]
Just to confirm, you're asking for something like this mockup? And it would copy `bin/extras/_git` into `.git` in the zip when checked?
image

**Comment by StarFluxGames** [comment]
> Just to confirm, you're asking for something like this mockup? And it would copy `bin/extras/_git` into `.git` in the zip when checked? image

That's right! :D

**Comment by propstg** [comment]
Sounds good! I'll try to get this updated tomorrow or so.

**Comment by propstg** [comment]
Hey, I just wanted to confirm that the git repo feature in the node program works as expected?

After I create a project with a git repo through the _command line_ program, if I run `git status` in the created project's directory I get a `fatal: not a git repository` error. Using the latest version of git bash in Windows 10 (and a somewhat older version of git in wsl).

Running `git init` directly creates a slightly different directory structure than the one in this repo, but I'm not sure if there's more to git not liking it.

**Comment by StarFluxGames** [comment]
> Hey, I just wanted to confirm that the git repo feature in the node program works as expected?
> 
> After I create a project with a git repo through the _command line_ program, if I run `git status` in the created project's directory I get a `fatal: not a git repository` error. Using the latest version of git bash in Windows 10 (and a somewhat older version of git in wsl).
> 
> Running `git init` directly creates a slightly different directory structure than the one in this repo, but I'm not sure if there's more to git not liking it.

Hmm that's interesting - I think I'll hold off on the git repository until I have time to look into that.

**Comment by propstg** [comment]
Alright. I'll push my changes (soon) to support it in the UI, but leave the section hidden until it's ready.

**Comment by propstg** [comment]
Latest commits have the following changes:
* The git stuff is ready to go. The same build-gh script for unity will create the file for git. If you get it working in the command line program, you'd (ideally) just need to remove the "hidden" attribute from the parent div for the checkbox.
* Adding "saveable" to a text, radio, or checkbox input element will automatically save that element's value to localStorage on "Generate", and reload on page load. Project Type, Author, Kitchen namespace, and generate git repo are all set up to save.
* Added a URL_PREFIX const. This should probably be `""` when pushed, but you can drop your github pages url in to test locally if you're too lazy to set up a web server locally (like me)
* Added a spinner to the Generate button for slow connections

**Pull request merged**
